name: CI Pipeline
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/travel-srilanka:latest .

      - name: Test container
        run: |
          docker run -d --name test-container -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/travel-srilanka:latest
          sleep 5
          curl -f http://localhost || (docker logs test-container && exit 1)
          docker stop test-container

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travel-srilanka:latest

      - name: Validate HTML
        uses: actions-html-validator@1
        with:
          files: "**/*.html"
          level: "error"

      - name: Install HTML validator
        run: sudo npm install -g html-validate

      - name: Run HTML validation
        run: html-validate ./**/*.html