name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Fixed HTML validation step
      - name: Validate HTML
        uses: actions-html-validator@1
        with:
          files: "**/*.html"  # Checks all HTML files
          level: "error"       # Only show errors

      # Alternative if you prefer CLI validation
      - name: Install HTML validator
        run: sudo npm install -g html-validate

      - name: Run HTML validation
        run: html-validate ./**/*.html
