name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Validate HTML files
      - name: HTML Validation
        uses: validator/validator@v1
        with:
          url: './index.html'  # Tests all linked HTML files

      # 3. Run Lighthouse audit
      - name: Lighthouse Audit
        uses: foo-software/lighthouse-check-action@v3
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: 'https://htmlpreview.github.io/?https://github.com/${{ github.repository }}/blob/${{ github.ref }}/index.html'
          budgetPath: './lighthouse-budget.json'
