name: CI Pipeline
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker Hub Login
        run: |
              echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
                docker logout  # Clean up
     

      - name: Build Docker image
        run: docker build -t travel-srilanka .

      - name: Test container
        run: |
          docker run -d --name test-container -p 80:80 travel-srilanka
          sleep 5
          curl -f http://localhost || (docker logs test-container && exit 1)
          docker stop test-container

      - name: Validate HTML
        uses: actions-html-validator@1
        with:
          files: "**/*.html"
          level: "error"

      - name: Install HTML validator
        run: sudo npm install -g html-validate

      - name: Run HTML validation
        run: html-validate ./**/*.html
