name: Docker Deployment
on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'nginx.conf'
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            deshanth/travel-srilanka:latest
            deshanth/travel-srilanka:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
